### ISSUE TITLE
default allowed hosts to `localhost`

### ISSUE THREAD

**Issue by josephabrahams** [istrategylabs/mo-django#11]

**Comment by jcarbaugh** [comment]
A default is set in [env.example](https://github.com/istrategylabs/mo-django/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/env.example#L4), which is intended to be copied to _.env_ when bootstrapping the project (and will be done automatically soon when I finish the bootstrap script). `ALLOWED_HOSTS` is also ignored when `DEBUG == True` so it will be bypassed under the normal conditions of local or Docker development.

**Comment by josephabrahams** [comment]
Would you ever enable DEBUG mode on an environment other an dev?

Seems like the current setup assumes that DEBUG == dev mode. 

Is there a case for separating this?

Joseph Abrahams | VP of Engineering
ISL <https://isl.co/> | 256.302.0500
Twitter <http://twitter.com/josephabrahams> | LinkedIn <https://www.linkedin.com/in/josephabrahams>

**Comment by jcarbaugh** [comment]
DEBUG shouldn't really be ever set on a publicly accessible site (which staging sometimes is and sometimes isn't).

ALLOWED_HOSTS being ignored while DEBUG is True isn't a mo-django thing, it's how Django works. So we'd have to work with that behavior even if we wanted DEBUG on in a non-dev environment.

**Comment by josephabrahams** [comment]
As we have to manually set all the config on Heroku, let's just remove {{ cookiecutter.domain_name }} entirely. Unless there's something I'm missing.

**Comment by jcarbaugh** [comment]
We're defaulting to `ALLOWED_HOSTS=*` in example.env now, which I believe is in line with this ticket.
