### ISSUE TITLE
use `forego start` to run the application locally

### ISSUE THREAD

**Issue by josephabrahams** [istrategylabs/mo-django#13]
Would rather use process manager to run the app so it's more similar to Heroku.

**Comment by josephabrahams** [comment]
This may mean modifying Procfile and adding a bin/web script to determine what environment you're in.

Open to discussion.

**Comment by jcarbaugh** [comment]
It would be best if the behavior of Procfile was consistent between environments. It's good to know that running the app with Procfile will run the full app + workers the exact same way it will in other environments, especially as a final test. We could include a _Procfile.dev_, which can be used by passing an argument to foreman, that has a more dev appropriate configuration. That would still allow Procfile to run the app using the deployment configuration, but allow us to run the Django dev server, gulp watch processes, and workers within foreman.

**Comment by josephabrahams** [comment]
This is something I've gone back and forth on. I've typically followed the trend of using a bin/web script (https://github.com/ddollar/foreman/issues/12#issuecomment-2655983 <https://github.com/ddollar/foreman/issues/12#issuecomment-2655983>) and kept Heroku-provided services out of the Procfile (Postgres, Redis) since they're brew installed and run globally on mac as well.

Joseph Abrahams | VP of Engineering
ISL <https://isl.co/> | 256.302.0500
Twitter <http://twitter.com/josephabrahams> | LinkedIn <https://www.linkedin.com/in/josephabrahams>

**Comment by jcarbaugh** [comment]
Oh yeah, external services shouldn't be in Procfile, mostly talking about processes like Celery workers and such that are part of the app. A web script for development that calls out to a dev-specific Procfile seems reasonable, but I think Procfile itself should be explicitly what will run on Heroku without varying or having to reference other files.
