### ISSUE TITLE
add .nvmrc file

### ISSUE THREAD

**Issue by josephabrahams** [istrategylabs/mo-django#15]
Ideally stay consistent w/ mo-static and mo-node where possible.

**Comment by josephabrahams** [comment]
Update documentation as such. Also, update `engines` key in package.json so heroku uses the same node version.

**Comment by jcarbaugh** [comment]
I started migrating the current mo-static over. That should take care of this once it's done.

**Comment by jcarbaugh** [comment]
Closing in favor of #19.
