### ISSUE TITLE
Replace Celery with rq?

### ISSUE THREAD

**Issue by jcarbaugh** [istrategylabs/mo-django#23]
rq is a lightweight job/worker system similar to Celery, but based solely on Redis. It gets rid of the complexity of Celery both in configuration and usage.

I'd prefer to replace Celery, which was never really properly configured in mo-django anyway. https://github.com/istrategylabs/mo-django/pull/5 switches to a fully working rq setup.

Thoughts?

**Comment by josephabrahams** [comment]
:+1:
