### ISSUE TITLE
Image task gets in endless repeat loop

### ISSUE THREAD

**Issue by thomasdegry** [istrategylabs/mo-django#3]
The Image task in Gulp kicks off when an image is added to the project or overwritten. When you save a new image while the image task is running it goes in an endless loop that it doesn't get out of. The gulp process takes over the CPU completely.

Let me know if you have issues replicating!

**Comment by jcarbaugh** [comment]
Ah, yep. It's writing the minified image to a watched path, causing that image to re-minified, again and again, forever.

**Comment by jcarbaugh** [comment]
Okay, we should think about the `src` and `dist` directories. Gotta keep it clean and compatible with Django's staticfiles.

**Comment by thomasdegry** [comment]
mo-static has the structure of a src folder and a public folder, if we want to keep it similar

**Comment by jcarbaugh** [comment]
Closing as this will be fixed for good in #19.
