### ISSUE TITLE
Remove obsolete `django-sslify` package and replace with SECURE_SSL_REDIRECT setting

### ISSUE THREAD

**Issue by akrawchyk** [istrategylabs/mo-django#51]
The `django-sslify` package was [created for django versions <1.8](https://github.com/rdegges/django-sslify#using-django-18-or-later). Django 1.8 or later doesn't need the package to force SSL.

Instead, we should set the `SECURE_SSL_REDIRECT` appropriately.

**Comment by CorneliusIV** [comment]
This was fixed in https://github.com/istrategylabs/mo-django/pull/53
