### ISSUE TITLE
remove default license

### ISSUE THREAD

**Issue by josephabrahams** [istrategylabs/mo-django#7]
Or make optional -> Apache

**Comment by jcarbaugh** [comment]
Have the inclusion of a license be a cookiecutter option? It's much harder to have a file generated conditionally than it is to change the content, so maybe an open source option that uses Apache if Y, otherwise puts all rights reserved in LICENSE?

**Comment by josephabrahams** [comment]
I'd advocate for removing altogether as client work doesn't need a license and having a `open-source-guidelines` repo for making any project open source.
